services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password

      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris

      - key: N8N_DEFAULT_LOCALE
        value: en
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: WEBHOOK_URL
        value: https://n8n-x8l1.onrender.com
      - key: N8N_HOST
        value: n8n-x8l1.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-x8l1.onrender.com

databases:
  - name: n8nDB
    region: oregon
    plan: free